{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doing.router",
    "module": "Router",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Router-0.0.1.jar",
          "url": "Router-0.0.1.jar",
          "size": 5834,
          "sha512": "95c24ef275c58b3143f3dd149f33a7bb5a929ac2d1f7096c51324237c3e4d781e212d9a83daa8e6cf58614f5fc3bde3425842e6ffc9ece8792c97d25402288b3",
          "sha256": "48e237fce5d7f691903021fc0f8cac451f1442749a36e01b184003616a2a3c05",
          "sha1": "98b93a389be3a979d6fc1ae41a297251d098e304",
          "md5": "13fb95d8974c7d2d2b3ca37479e0ef6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Router-0.0.1.jar",
          "url": "Router-0.0.1.jar",
          "size": 5834,
          "sha512": "95c24ef275c58b3143f3dd149f33a7bb5a929ac2d1f7096c51324237c3e4d781e212d9a83daa8e6cf58614f5fc3bde3425842e6ffc9ece8792c97d25402288b3",
          "sha256": "48e237fce5d7f691903021fc0f8cac451f1442749a36e01b184003616a2a3c05",
          "sha1": "98b93a389be3a979d6fc1ae41a297251d098e304",
          "md5": "13fb95d8974c7d2d2b3ca37479e0ef6d"
        }
      ]
    }
  ]
}
