{
  "formatVersion": "1.1",
  "component": {
    "group": "com.doing.router",
    "module": "RouterPlugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "RouterPlugin-0.0.1.jar",
          "url": "RouterPlugin-0.0.1.jar",
          "size": 5832,
          "sha512": "ec92a617e418bdbac5aa42449e565d2ba0f198351114dc06ee17629e90f98e2df6e7873f1b8bd707780cce92728c6a970bb4c282b12a10c96efff3e047b42488",
          "sha256": "48b3fcd77f552ab379a9e901b5f8ac67651c77971a563031f5f8ad3938d7dda6",
          "sha1": "6458a8804a15b789fcb3a122a54dd8d5f912a467",
          "md5": "c988bbc03a6965b30ad5902db8df2a99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "RouterPlugin-0.0.1.jar",
          "url": "RouterPlugin-0.0.1.jar",
          "size": 5832,
          "sha512": "ec92a617e418bdbac5aa42449e565d2ba0f198351114dc06ee17629e90f98e2df6e7873f1b8bd707780cce92728c6a970bb4c282b12a10c96efff3e047b42488",
          "sha256": "48b3fcd77f552ab379a9e901b5f8ac67651c77971a563031f5f8ad3938d7dda6",
          "sha1": "6458a8804a15b789fcb3a122a54dd8d5f912a467",
          "md5": "c988bbc03a6965b30ad5902db8df2a99"
        }
      ]
    }
  ]
}
